title: Soupe UI Components
url: "https://cheeryworks.org/soupe-ui-components"
baseurl:

collections:
  portfolios:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-paginate"
  - "jekyll-multiple-languages-plugin"
  - "jekyll-sitemap"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - Dockerfile
  - "*.iml"
  - "*.sh"
  - docs

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "portfolios"
    values:
      layout: "portfolio"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

languages: [ "en", "zh" ]
exclude_from_localizations: [ "javascript", "css", "_posts", "blog" ]
